### ISSUE TITLE
get cluster number of new image in already clustered algorithm

### ISSUE THREAD

**Issue by learnermaxRL** [elcorto/imagecluster#12]
how to assign cluster to new example?

**Comment by elcorto** [comment]
Would you mind elaborating a bit more?

**Comment by elcorto** [comment]
Closing due to inactive OP.

In any case, if I had to guess what the question is about, then the closest one already asked is probably #2, but note the the reference to `main()` therein is no longer valid, since that was removed f9ad7198c0f9cc814f70633bb2dcadead1e96cdb. Please use something like [this example](https://github.com/elcorto/imagecluster/blob/master/examples/example_api_minimal.py) instead.
