### ISSUE TITLE
is it possible to add a new image without re-clustering?

### ISSUE THREAD

**Issue by ianni67** [elcorto/imagecluster#2]
Your work is intriguing and I would like to understand what happens if I have a new image to be added to the database. The NN paradigm should allow me to parse the tree and look for the node that is nearest to my new image. What does happen with your software in such a case?

**Comment by elcorto** [comment]
The `main.main()` function is only a very simple example of how one might use the library and lacks any kind of workflow support. Currently, adding new images is only possible by removing `/path/to/pics/imagecluster/fingerprints.pk`. In that case `main()` will calculate all fingerprints again, including the new ones, else it just uses the fingerprints file and does the clustering right away. Since clustering is much faster than calculating the fingerprints (run image through the NN) , you would rather want to avoid re-calculating all fingerprints. It is easy to extend `main()` in that regard, i.e. check if the database is present, and then skip the calculation for already present fingerprints. In that case, one would also change the hard-coded location of `fingerprints.pk` and add an option to pass the location of such a file (e.g. the global fingerprints database of your whole image collection), which then gets updated.
